warnings_are_errors: false
language: r
r:
  - release
cache: packages
r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libssh-dev

# safelist
branches:
  only:
  - master
  - develop
